version: "3.7"
services:
  webserver:
    build:
      args:
        user: syam
        uid: 6666
      context: ./
      dockerfile: Dockerfile
    image: busbooking
    container_name: busbooking-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - busbooking

  db:
    image: mysql:5.7
    container_name: busbooking-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'bus_booking'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_USER: 'root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - busbooking

  nginx:
    image: nginx:alpine
    container_name: busbooking-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./sites:/etc/nginx/conf.d/
    networks:
      - busbooking

networks:
  busbooking:
    driver: bridge
